create the first files
glebeckaya/webix-start pull request #1
Opened 2021-04-07 14:17 UTC by glebeckaya

2021-04-07 14:49 UTC, olimed commented on src/testdata.js
> +var small_film_set = [
почему ты тут используешь var?

2021-04-07 14:49 UTC, olimed commented on index.html
> +  <script type="text/javascript" charset="utf-8">
создай правильную структуру твоего приложения. вынеси все то. что в тэге <script> в отдельный файл

2021-04-07 14:49 UTC, olimed commented on index.html
> +    var header = {
пользуйся let  и const (этот комментарий я не буду писать после каждого var,  но их нужно все исправить)

2021-04-07 14:49 UTC, olimed commented on index.html
> +				{view:"button", id:"profile-button", type: "icon", icon:"mdi mdi-account", label:"Profile", autowidth: true, css: "webix_transparent"}
старайся придерживаться одних правил линта

2021-04-07 14:49 UTC, olimed commented on index.html
> +      id: "myHeader",
название айдишек "my...." лучше не использовать, если тебе не нужно к нему обращаться, то лучше не писать id

2021-04-07 14:49 UTC, olimed commented on index.html
> +					id:"mylist",
смотри комментарий выше про id

2021-04-07 14:49 UTC, olimed commented on index.html
> +				{ view:"button", type: "icon", icon:"mdi mdi-check", label:"Connected", css: "webix_transparent"}
можо использовать template вместо button

2021-04-07 14:49 UTC, olimed commented on index.html
> +          id:"log_form",
смотри коммент про id, именование переменных должно быть в одном стиле

2021-04-07 14:49 UTC, olimed commented on index.html
> +            { view:"text", type:"number", label:"Votes", name:"votes"},
name можно не использовать, так как  оно сейчас не нужно

2021-04-07 14:49 UTC, olimed commented on index.html
> +			id:"myApp",
смотри коммент про id выше

2021-04-07 14:57 UTC, glebeckaya commented on index.html
> +            { view:"text", type:"number", label:"Votes", name:"votes"},
name удален

2021-04-07 15:07 UTC, Zwillinge requested changes

2021-04-07 15:07 UTC, Zwillinge commented on index.html
> +    [view_id="side"]>.webix_view {
это очень ненадежно. ты или другой программист на том же проекте может поменять id или убрать его, и отвалятся стили. мы задаем класс для view с помощью свойства css в конфиге

2021-04-07 15:08 UTC, Zwillinge commented on index.html
> +				{ view:"button", type: "icon", icon:"mdi mdi-check", label:"Connected", css: "webix_transparent"}
и так даже лучше, потому что у кнопки есть hover-стили, которые показывают что она кликабельна. а это простой не интерактивный лейбл 

view:"label" еще можно

2021-04-07 15:13 UTC, glebeckaya commented on index.html
> +				{ view:"button", type: "icon", icon:"mdi mdi-check", label:"Connected", css: "webix_transparent"}
заменила на template

2021-04-07 15:23 UTC, glebeckaya commented on index.html
> +    [view_id="side"]>.webix_view {
селектор исправлен, добавила класс "side-section" в конфиг элемента side

2021-04-07 15:28 UTC, glebeckaya commented on index.html
> +      id: "myHeader",
id удален

2021-04-07 15:29 UTC, glebeckaya commented on index.html
> +					id:"mylist",
id удален

2021-04-07 15:39 UTC, glebeckaya commented on index.html
> +          id:"log_form",
id переименован на "form-films", так как с данными формы предполагается дальнейшая работа, я так понимаю, и потребуется обращаться к ней

2021-04-07 15:39 UTC, glebeckaya commented on index.html
> +			id:"myApp",
id удален

2021-04-07 15:44 UTC, glebeckaya commented on index.html
> +				{view:"button", id:"profile-button", type: "icon", icon:"mdi mdi-account", label:"Profile", autowidth: true, css: "webix_transparent"}
исправила, буду следить за этим

2021-04-07 15:45 UTC, glebeckaya commented on index.html
> +    var header = {
исправлено

2021-04-07 15:51 UTC, glebeckaya commented on src/testdata.js
> +var small_film_set = [
исправила, этот файл брала из документа на домашнее задание (предположила, что оно приходит к разработчику в таком виде, и нельзя изменять его, поэтому и дальше в коде использовала var везде, чтобы не мешать старый и новый синтаксис)

2021-04-07 16:05 UTC, glebeckaya commented on index.html
> +  <script type="text/javascript" charset="utf-8">
script вынесла в отдельный файл

2021-04-07 17:00 UTC, olimed commented on src/index.js
> +var header = {
не испоьзуй var

2021-04-07 17:00 UTC, olimed commented on src/index.js
> +        {view:"button", id:"profile-button", type: "icon", icon:"mdi mdi-account", label:"Profile", autowidth: true, css: "webix_transparent"}
зачем тут id?

2021-04-07 17:00 UTC, olimed commented on src/index.js
> +      id: "form-films",
зачем тут id?

2021-04-07 18:42 UTC, glebeckaya commented on src/index.js
> +var header = {
заменила на const

2021-04-07 18:44 UTC, glebeckaya commented on src/index.js
> +        {view:"button", id:"profile-button", type: "icon", icon:"mdi mdi-account", label:"Profile", autowidth: true, css: "webix_transparent"}
удалила id

2021-04-07 18:45 UTC, glebeckaya commented on src/index.js
> +      id: "form-films",
удалила id

2021-04-07 18:51 UTC, Zwillinge requested changes

2021-04-07 18:51 UTC, Zwillinge commented on js/index.js
> +      view: "datatable",
на картинке у таблицы только вертикальный скролл бар, а у тебя оба

2021-04-07 18:56 UTC, Zwillinge commented on js/index.js
> +            width: 200,
у листа ширина 200 и у родителя minWidth 200 (дублируются размеры). в таком случае надо, если у нас горизонтальный layout и внутри лежат несколько рядов, внутри нет колонок, родитель принимает размер фиксированного child (здесь это лист). 

честнее было бы задать width (начальная ширина) и minWidth (лимит для ресайзера) для layout.

2021-04-07 19:10 UTC, glebeckaya commented on js/index.js
> +      view: "datatable",
горизонтальный скролл бар убрала

2021-04-07 19:12 UTC, glebeckaya commented on js/index.js
> +            width: 200,
убрала width у элемента list, задала начальную и минимальную ширину родителю

2021-04-07 19:34 UTC, Zwillinge commented on js/index.js
> +      view: "datatable",
только не через css. надо это отрегулировать свойством scroll на конфиге таблицы

2021-04-07 19:57 UTC, glebeckaya commented on js/index.js
> +      view: "datatable",
исправила через свойство scroll

2021-04-08 06:18 UTC, olimed approved these changes

2021-04-08 06:26 UTC, Zwillinge approved these changes

2021-04-08 06:46 UTC, merged