lesson5
glebeckaya/webix-start pull request #5
Opened 2021-04-13 15:41 UTC by glebeckaya

2021-04-13 16:08 UTC, olimed commented on js/index.js
> +        } else return obj;
альтернатива твоему способу:
 if (obj.age < 26) {
       obj.$css = "row-highlight";
  }
return obj;

2021-04-13 16:08 UTC, olimed commented on js/views/admin/adminTable.js
> +            autoConfig: true,
это свойство используется для конфигурации таблицы из данных
https://docs.webix.com/api__ui.datatable_autoconfig_config.html
ты используешь column для конфигурации таблицы, возможно autoConfig свойство не нужно в даном случае использовать

2021-04-13 16:08 UTC, olimed commented on js/views/admin/adminTable.js
> +}
ты много где используешь похожие функции, как вариант ты можешь вынести в файл функцию и передавать нужный текст, id и вьюшку. А эту функцию потом импортировать в нужные места
export function showConfirmMessage(id, viewId){
const view = $$(viewId);
if (!view) return;
webix.confirm({
        text: `Do you really want to delete "${view.data.pull[id].value}"?`
    }).then(
        () => view.remove(id);
    );

}

2021-04-13 18:10 UTC, glebeckaya commented on js/views/admin/adminTable.js
> +}
вынесла функцию в отдельный файл

2021-04-13 18:10 UTC, glebeckaya commented on js/views/admin/adminTable.js
> +            autoConfig: true,
удалила autoConfig

2021-04-13 18:10 UTC, glebeckaya commented on js/index.js
> +        } else return obj;
поправила и вернула в list с юзерами scheme с таким же условием, так как у новых строк при их добавлении background не менялся

2021-04-13 18:24 UTC, Zwillinge requested changes

2021-04-13 18:24 UTC, Zwillinge commented on js/index.js
> +$$("dataFilms").getColumnConfig("category").collection.sync($$("dataCategories"));
можно просто в конфиге колонки прописать `collection:categories`. а так ты получается синхронизируешь slave-a коллекции, делая его мастером по отношению к опциям колонки. то же самое про селектор, там будет options:categories  

если же ты намеренно хочешь cобрать все синхронизации в одном месте, то тогда надо хотя бы к categories коллекции колонку и селектор привязываешь, но не к таблице в админке

2021-04-13 18:24 UTC, Zwillinge commented on js/index.js
> +        if (obj.age < 26) {
вообще такие вещи внутри фильтра делать странно. ф-ция должна заниматься только тем, что нужно для фильтрации. а $css это для схемы

2021-04-13 18:24 UTC, Zwillinge commented on styles/styles.css
> +[view_id="dataFilms"] .cell-rank .webix_first,
не надо привязывать css к view_id. айди могут поменять или убрать, и не будут ожидать что он него зависит css. для таких случаев надо задавать свойство css на конфиге таблицы, это задаст собственный класс для неё

2021-04-13 18:24 UTC, Zwillinge commented on js/views/admin/adminTable.js
> +            editable: true,
нет возможности отредактировать value

2021-04-13 20:08 UTC, glebeckaya commented on js/index.js
> +        if (obj.age < 26) {
просто если убрать filter, то при первой отрисовке функция в схеме не срабатывает и нужные строки не подкрашиваются. подкрашиваются только для новых строк, удовлетворяющих этому условию, когда метод add отрабатывает..

2021-04-13 20:56 UTC, glebeckaya commented on js/index.js
> +$$("dataFilms").getColumnConfig("category").collection.sync($$("dataCategories"));
переписала, сделала мастером categories

2021-04-13 20:57 UTC, glebeckaya commented on styles/styles.css
> +[view_id="dataFilms"] .cell-rank .webix_first,
поняла, убрала привязку к id

2021-04-13 20:57 UTC, glebeckaya commented on js/views/admin/adminTable.js
> +            editable: true,
дописала)

2021-04-14 06:29 UTC, Zwillinge commented on js/index.js
> +        if (obj.age < 26) {
да, при синхронизации схема работает только у мастер компонента. она же преобразует данные, а данные на всех общие. в таких случаях надо задавать схему для мастер коллекции

2021-04-14 06:37 UTC, Zwillinge requested changes

2021-04-14 06:37 UTC, Zwillinge commented on js/views/users/list.js
> +                    showConfirmMessage(id, this, "name");
удаление происходит из slave, а на надо из мастера. поэтому в чарте изменения не отражаются

2021-04-14 06:37 UTC, Zwillinge commented on js/views/dashboard/datatable.js
> +                    showConfirmMessage(id, categories, "title");
это же таблица с данными. почему происходит удаление из категорий, а не из неё?

2021-04-14 07:20 UTC, glebeckaya commented on js/views/dashboard/datatable.js
> +                    showConfirmMessage(id, categories, "title");
исправила косяк

2021-04-14 07:20 UTC, glebeckaya commented on js/views/users/list.js
> +                    showConfirmMessage(id, this, "name");
исправила, удаляю из мастера

2021-04-14 07:20 UTC, glebeckaya commented on js/index.js
> +        if (obj.age < 26) {
спасибо! задала схему для мастер коллекции

2021-04-14 07:26 UTC, Zwillinge approved these changes

2021-04-14 07:37 UTC, olimed approved these changes

2021-04-14 07:37 UTC, merged